name: "Deploy Laravel App"
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          composer install
          npm install
      - name: Build application
        run: |
          npm run dev
      - name: Deploy application
        uses: appleboy/ssh-action@master
        with:
          host: 143.244.154.146
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/html/
            rm -rf *
            mv ~/project/* .
            chmod -R 777 storage/
            php artisan cache:clear
            php artisan view:clear
            php artisan config:cache
            php artisan route:cache
