name: Laravel Deployment

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - name: Laravel Deploy
        # You may pin to the exact commit or the version.
        # uses: ngocquyhoang/laravel-deploy@44ec6bf06ce9f68f68f614033fb57a8851f60b53
      uses: ngocquyhoang/laravel-deploy@laravel-custom-port
      with:
        # Deploy user
        user: ${{ secrets.SSH_USERNAME }}
        # Deploy host
        host: ${{ secrets.HOST }}
        # Path source on server
        path: /var/www/laravel
        # Deploy owner
        owner: ${{ secrets.SSH_USERNAME }}
      env:
        DEPLOY_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
